Repository SBNSoftware/sbnobj, pull requests merged in 2021-07, with the labels that each got.

#13 Updates to Stub objects
  sbnobj/Common/Reco/Stub.cc
  sbnobj/Common/Reco/Stub.cxx
  sbnobj/Common/Reco/Stub.h
  sbnobj/Common/Reco/VertexHit.h
  sbnobj/Common/Reco/classes_def.xml
Labels: enhancement

#19 Razzle Dazzle PID
  sbnobj/Common/Reco/CMakeLists.txt
  sbnobj/Common/Reco/MVAPID.cc
  sbnobj/Common/Reco/MVAPID.h
  sbnobj/Common/Reco/ScatterClosestApproach.cc
  sbnobj/Common/Reco/ScatterClosestApproach.h
  sbnobj/Common/Reco/StoppingChi2Fit.cc
  sbnobj/Common/Reco/StoppingChi2Fit.h
  sbnobj/Common/Reco/classes.h
  sbnobj/Common/Reco/classes_def.xml
Labels: enhancement

#22 Updates to TrackSkim object. Add in end-point-hit information and truth information.
  sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
  sbnobj/Common/Calibration/classes_def.xml
Labels: enhancement

#20 Refactor configs and products out of sbncode for MeVPrtl Event Generator
  sbnobj/Common/CMakeLists.txt
  sbnobj/Common/EventGen/CMakeLists.txt
  sbnobj/Common/EventGen/MeVPrtl/CMakeLists.txt
  sbnobj/Common/EventGen/MeVPrtl/KaonParent.cxx
  sbnobj/Common/EventGen/MeVPrtl/KaonParent.h
  sbnobj/Common/EventGen/MeVPrtl/MeVPrtlDecay.h
  sbnobj/Common/EventGen/MeVPrtl/MeVPrtlFlux.h
  sbnobj/Common/EventGen/MeVPrtl/MeVPrtlTruth.cxx
  sbnobj/Common/EventGen/MeVPrtl/MeVPrtlTruth.h
  sbnobj/Common/EventGen/MeVPrtl/classes.h
  sbnobj/Common/EventGen/MeVPrtl/classes_def.xml
Labels: maintenance

#21 Updates to Stub Objects for Space Charge
  sbnobj/Common/Reco/Stub.h
  sbnobj/Common/Reco/VertexHit.h
  sbnobj/Common/Reco/classes_def.xml
Labels: maintenance

#23 Fix to Missing FileEntry for sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
  sbnobj/Common/Calibration/CMakeLists.txt
Labels: bug
