Repository SBNSoftware/sbnobj, pull requests merged in 2025-03, with the labels that each got.

#122 Add hit goodness to sbn::HitInfo
  sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
  sbnobj/Common/Calibration/classes_def.xml
Labels: enhancement

#123 Add category to enum for unused channel
  sbnobj/SBND/CRT/CRTEnums.hh
Labels: enhancement, minor

#125 Add Dictionary
  sbnobj/SBND/CRT/classes_def.xml
Labels: bug
